[2023-08-27T07:27:30.987+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: nikeProducts_dag.extract_task manual__2023-08-27T07:22:28.334789+00:00 [queued]>
[2023-08-27T07:27:30.993+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: nikeProducts_dag.extract_task manual__2023-08-27T07:22:28.334789+00:00 [queued]>
[2023-08-27T07:27:30.993+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-08-27T07:27:30.994+0000] {taskinstance.py:1363} INFO - Starting attempt 2 of 2
[2023-08-27T07:27:30.994+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-08-27T07:27:31.002+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): extract_task> on 2023-08-27 07:22:28.334789+00:00
[2023-08-27T07:27:31.007+0000] {standard_task_runner.py:55} INFO - Started process 450 to run task
[2023-08-27T07:27:31.010+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'nikeProducts_dag', 'extract_task', 'manual__2023-08-27T07:22:28.334789+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/nikeProducts_dag.py', '--cfg-path', '/tmp/tmpiek76565']
[2023-08-27T07:27:31.012+0000] {standard_task_runner.py:83} INFO - Job 13: Subtask extract_task
[2023-08-27T07:27:31.059+0000] {task_command.py:376} INFO - Running <TaskInstance: nikeProducts_dag.extract_task manual__2023-08-27T07:22:28.334789+00:00 [running]> on host 56699fd2e5f2
[2023-08-27T07:27:31.104+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=nikeProducts_dag
AIRFLOW_CTX_TASK_ID=extract_task
AIRFLOW_CTX_EXECUTION_DATE=2023-08-27T07:22:28.334789+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-27T07:22:28.334789+00:00
[2023-08-27T07:27:31.105+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/products_scripts/get_data.py", line 11, in main
    input_files = os.listdir(f"{directory}/")
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scrapper/data/products/'
[2023-08-27T07:27:31.114+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=nikeProducts_dag, task_id=extract_task, execution_date=20230827T072228, start_date=20230827T072730, end_date=20230827T072731
[2023-08-27T07:27:31.121+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 13 for task extract_task ([Errno 2] No such file or directory: '/opt/airflow/scrapper/data/products/'; 450)
[2023-08-27T07:27:31.144+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-08-27T07:27:31.165+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
