[2023-08-27T07:22:29.724+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: nikeProducts_dag.extract_task manual__2023-08-27T07:22:28.334789+00:00 [queued]>
[2023-08-27T07:22:29.731+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: nikeProducts_dag.extract_task manual__2023-08-27T07:22:28.334789+00:00 [queued]>
[2023-08-27T07:22:29.732+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-08-27T07:22:29.732+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2023-08-27T07:22:29.733+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-08-27T07:22:29.741+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): extract_task> on 2023-08-27 07:22:28.334789+00:00
[2023-08-27T07:22:29.746+0000] {standard_task_runner.py:55} INFO - Started process 199 to run task
[2023-08-27T07:22:29.750+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'nikeProducts_dag', 'extract_task', 'manual__2023-08-27T07:22:28.334789+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/nikeProducts_dag.py', '--cfg-path', '/tmp/tmp69jsvx9o']
[2023-08-27T07:22:29.752+0000] {standard_task_runner.py:83} INFO - Job 11: Subtask extract_task
[2023-08-27T07:22:29.807+0000] {task_command.py:376} INFO - Running <TaskInstance: nikeProducts_dag.extract_task manual__2023-08-27T07:22:28.334789+00:00 [running]> on host 56699fd2e5f2
[2023-08-27T07:22:29.859+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=nikeProducts_dag
AIRFLOW_CTX_TASK_ID=extract_task
AIRFLOW_CTX_EXECUTION_DATE=2023-08-27T07:22:28.334789+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-27T07:22:28.334789+00:00
[2023-08-27T07:22:29.861+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/products_scripts/get_data.py", line 11, in main
    input_files = os.listdir(f"{directory}/")
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scrapper/data/products/'
[2023-08-27T07:22:29.871+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=nikeProducts_dag, task_id=extract_task, execution_date=20230827T072228, start_date=20230827T072229, end_date=20230827T072229
[2023-08-27T07:22:29.879+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 11 for task extract_task ([Errno 2] No such file or directory: '/opt/airflow/scrapper/data/products/'; 199)
[2023-08-27T07:22:29.925+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-08-27T07:22:29.950+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
