[2023-08-27T07:13:48.944+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: nikeProducts_dag.extract_task manual__2023-08-27T07:13:47.791836+00:00 [queued]>
[2023-08-27T07:13:48.951+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: nikeProducts_dag.extract_task manual__2023-08-27T07:13:47.791836+00:00 [queued]>
[2023-08-27T07:13:48.952+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-08-27T07:13:48.952+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2023-08-27T07:13:48.953+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-08-27T07:13:48.962+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): extract_task> on 2023-08-27 07:13:47.791836+00:00
[2023-08-27T07:13:48.968+0000] {standard_task_runner.py:55} INFO - Started process 248 to run task
[2023-08-27T07:13:48.973+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'nikeProducts_dag', 'extract_task', 'manual__2023-08-27T07:13:47.791836+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/nikeProducts_dag.py', '--cfg-path', '/tmp/tmpn1xgf8ic']
[2023-08-27T07:13:48.975+0000] {standard_task_runner.py:83} INFO - Job 5: Subtask extract_task
[2023-08-27T07:13:49.041+0000] {task_command.py:376} INFO - Running <TaskInstance: nikeProducts_dag.extract_task manual__2023-08-27T07:13:47.791836+00:00 [running]> on host f84f332fdb4d
[2023-08-27T07:13:49.094+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=nikeProducts_dag
AIRFLOW_CTX_TASK_ID=extract_task
AIRFLOW_CTX_EXECUTION_DATE=2023-08-27T07:13:47.791836+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-27T07:13:47.791836+00:00
[2023-08-27T07:13:49.096+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/products_scripts/get_data.py", line 11, in main
    input_files = os.listdir(f"{directory}/")
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scrapper/data/products/'
[2023-08-27T07:13:49.105+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=nikeProducts_dag, task_id=extract_task, execution_date=20230827T071347, start_date=20230827T071348, end_date=20230827T071349
[2023-08-27T07:13:49.112+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 5 for task extract_task ([Errno 2] No such file or directory: '/opt/airflow/scrapper/data/products/'; 248)
[2023-08-27T07:13:49.147+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-08-27T07:13:49.167+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
