[2023-08-26T03:40:41.901+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: nikeProducts_dag.extract_task manual__2023-08-26T03:40:39.998217+00:00 [queued]>
[2023-08-26T03:40:41.907+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: nikeProducts_dag.extract_task manual__2023-08-26T03:40:39.998217+00:00 [queued]>
[2023-08-26T03:40:41.907+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-08-26T03:40:41.908+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2023-08-26T03:40:41.908+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-08-26T03:40:41.915+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): extract_task> on 2023-08-26 03:40:39.998217+00:00
[2023-08-26T03:40:41.919+0000] {standard_task_runner.py:55} INFO - Started process 237 to run task
[2023-08-26T03:40:41.923+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'nikeProducts_dag', 'extract_task', 'manual__2023-08-26T03:40:39.998217+00:00', '--job-id', '113', '--raw', '--subdir', 'DAGS_FOLDER/nikeProducts_dag.py', '--cfg-path', '/tmp/tmp5iy2wgf7']
[2023-08-26T03:40:41.924+0000] {standard_task_runner.py:83} INFO - Job 113: Subtask extract_task
[2023-08-26T03:40:41.968+0000] {task_command.py:376} INFO - Running <TaskInstance: nikeProducts_dag.extract_task manual__2023-08-26T03:40:39.998217+00:00 [running]> on host 9f01d644bb11
[2023-08-26T03:40:42.013+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=nikeProducts_dag
AIRFLOW_CTX_TASK_ID=extract_task
AIRFLOW_CTX_EXECUTION_DATE=2023-08-26T03:40:39.998217+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-26T03:40:39.998217+00:00
[2023-08-26T03:40:42.015+0000] {logging_mixin.py:120} INFO - products mapped to products_etl.csv
[2023-08-26T03:40:42.016+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/products_scripts/get_data.py", line 17, in main
    df = pd.read_csv(os.path.join(AIRFLOW_HOME, "dags", "files", "input", "products", input_file))
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/files/input/products/products'
[2023-08-26T03:40:42.025+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=nikeProducts_dag, task_id=extract_task, execution_date=20230826T034039, start_date=20230826T034041, end_date=20230826T034042
[2023-08-26T03:40:42.034+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 113 for task extract_task ([Errno 2] No such file or directory: '/opt/airflow/dags/files/input/products/products'; 237)
[2023-08-26T03:40:42.055+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-08-26T03:40:42.073+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
