[2023-08-27T08:08:37.566+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: nikeProducts_dag.extract_task manual__2023-08-27T08:08:36.131741+00:00 [queued]>
[2023-08-27T08:08:37.575+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: nikeProducts_dag.extract_task manual__2023-08-27T08:08:36.131741+00:00 [queued]>
[2023-08-27T08:08:37.576+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-08-27T08:08:37.577+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2023-08-27T08:08:37.578+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-08-27T08:08:37.587+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): extract_task> on 2023-08-27 08:08:36.131741+00:00
[2023-08-27T08:08:37.593+0000] {standard_task_runner.py:55} INFO - Started process 138 to run task
[2023-08-27T08:08:37.597+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'nikeProducts_dag', 'extract_task', 'manual__2023-08-27T08:08:36.131741+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/nikeProducts_dag.py', '--cfg-path', '/tmp/tmpc8485q6j']
[2023-08-27T08:08:37.600+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask extract_task
[2023-08-27T08:08:37.664+0000] {task_command.py:376} INFO - Running <TaskInstance: nikeProducts_dag.extract_task manual__2023-08-27T08:08:36.131741+00:00 [running]> on host 82dd2c666eac
[2023-08-27T08:08:37.718+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=nikeProducts_dag
AIRFLOW_CTX_TASK_ID=extract_task
AIRFLOW_CTX_EXECUTION_DATE=2023-08-27T08:08:36.131741+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-27T08:08:36.131741+00:00
[2023-08-27T08:08:37.721+0000] {logging_mixin.py:120} INFO - nike_22AUG2023_1912.csv mapped to products_etl.csv
[2023-08-27T08:08:37.906+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/products_scripts/get_data.py", line 17, in main
    df.to_csv(raw_destination)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 3482, in to_csv
    storage_options=storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/format.py", line 1105, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/formats/csvs.py", line 243, in save
    storage_options=self.storage_options,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data_warehouse/data/products_etl.csv'
[2023-08-27T08:08:37.918+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=nikeProducts_dag, task_id=extract_task, execution_date=20230827T080836, start_date=20230827T080837, end_date=20230827T080837
[2023-08-27T08:08:37.927+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 4 for task extract_task ([Errno 2] No such file or directory: '/opt/airflow/data_warehouse/data/products_etl.csv'; 138)
[2023-08-27T08:08:37.973+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-08-27T08:08:37.997+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
