[2023-08-27T07:13:51.536+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: nikeSales_dag.extract_task manual__2023-08-27T07:13:50.198036+00:00 [queued]>
[2023-08-27T07:13:51.543+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: nikeSales_dag.extract_task manual__2023-08-27T07:13:50.198036+00:00 [queued]>
[2023-08-27T07:13:51.543+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-08-27T07:13:51.544+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2023-08-27T07:13:51.544+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-08-27T07:13:51.552+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): extract_task> on 2023-08-27 07:13:50.198036+00:00
[2023-08-27T07:13:51.557+0000] {standard_task_runner.py:55} INFO - Started process 251 to run task
[2023-08-27T07:13:51.561+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'nikeSales_dag', 'extract_task', 'manual__2023-08-27T07:13:50.198036+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/nikeSales_dag.py', '--cfg-path', '/tmp/tmptubv4_sj']
[2023-08-27T07:13:51.563+0000] {standard_task_runner.py:83} INFO - Job 6: Subtask extract_task
[2023-08-27T07:13:51.611+0000] {task_command.py:376} INFO - Running <TaskInstance: nikeSales_dag.extract_task manual__2023-08-27T07:13:50.198036+00:00 [running]> on host f84f332fdb4d
[2023-08-27T07:13:51.658+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=nikeSales_dag
AIRFLOW_CTX_TASK_ID=extract_task
AIRFLOW_CTX_EXECUTION_DATE=2023-08-27T07:13:50.198036+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-27T07:13:50.198036+00:00
[2023-08-27T07:13:51.659+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/sales_scripts/get_data.py", line 11, in main
    input_files = os.listdir(f"{directory}/")
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/scrapper/data/sales/'
[2023-08-27T07:13:51.669+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=nikeSales_dag, task_id=extract_task, execution_date=20230827T071350, start_date=20230827T071351, end_date=20230827T071351
[2023-08-27T07:13:51.676+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 6 for task extract_task ([Errno 2] No such file or directory: '/opt/airflow/scrapper/data/sales/'; 251)
[2023-08-27T07:13:51.692+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-08-27T07:13:51.712+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
